/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useFBX, useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useControls } from "leva";
import React, { useEffect, useRef, useState } from "react";
import * as THREE from "three";

export function Avatar(props) {
  const { animation, dress = "default", gender = "male", size = { height: 170, weight: 70 } } = props;
  const { headFollow, wireframe } = useControls({
    headFollow: false,
    wireframe: false,
  });
  const group = useRef();
  const [currentDress, setCurrentDress] = useState(dress);
  const [isAdmiring, setIsAdmiring] = useState(false);
  const idleTimer = useRef(null);
  const lastDressChange = useRef(dress);
  
  // Load the model
  const { nodes, materials, animations } = useGLTF("/models/646d9dcdc8a5f5bddbfac913.glb");
  
  // Load animations
  const { animations: typingAnimation } = useFBX("/animations/Typing.fbx");
  const { animations: standingAnimation } = useFBX("/animations/Standing Idle.fbx");
  const { animations: fallingAnimation } = useFBX("/animations/Falling Idle.fbx");
  
  // Name the animations
  typingAnimation[0].name = "Typing";
  standingAnimation[0].name = "Standing";
  fallingAnimation[0].name = "Falling";
  
  // Setup animations
  const { actions } = useAnimations([typingAnimation[0], standingAnimation[0], fallingAnimation[0]], group);

  // Calculate gender-specific scale
  const calculateGenderScale = () => {
    const baseScale = {
      male: { x: 1, y: 1, z: 1 },
      female: { x: 0.9, y: 0.95, z: 0.9 } // Slightly smaller and more slender for female
    };
    return baseScale[gender];
  };

  // Calculate size scale
  const calculateSizeScale = () => {
    const baseHeight = 170;
    const baseWeight = 70;
    const heightScale = size.height / baseHeight;
    const weightScale = Math.pow(size.weight / baseWeight, 0.33);
    
    return {
      x: weightScale,
      y: heightScale,
      z: weightScale
    };
  };

  // Apply combined scale (gender + size)
  useEffect(() => {
    if (group.current) {
      const genderScale = calculateGenderScale();
      const sizeScale = calculateSizeScale();
      
      const finalScale = {
        x: genderScale.x * sizeScale.x,
        y: genderScale.y * sizeScale.y,
        z: genderScale.z * sizeScale.z
      };
      
      group.current.scale.set(finalScale.x, finalScale.y, finalScale.z);
      
      // Adjust position to keep feet on ground
      const baseY = -0.5;
      const heightOffset = (finalScale.y - 1) * 0.5;
      group.current.position.y = baseY + heightOffset;
    }
  }, [gender, size]);

  // Idle animation function with random gestures
  const startIdleAnimation = () => {
    if (actions["Standing"]) {
      actions["Standing"].reset().fadeIn(0.5).play();
      actions["Standing"].setEffectiveTimeScale(0.5);
      return () => actions["Standing"].fadeOut(0.5);
    }
  };

  // Start idle animation on mount
  useEffect(() => {
    const cleanup = startIdleAnimation();
    return () => cleanup && cleanup();
  }, []);

  // Handle dress change animation
  useEffect(() => {
    if (dress !== lastDressChange.current) {
      setIsAdmiring(true);
      
      // Admiring animation sequence
      const spine = group.current.getObjectByName("Spine2");
      const head = group.current.getObjectByName("Head");
      const rightUpperArm = group.current.getObjectByName("RightUpperArm");
      const rightLowerArm = group.current.getObjectByName("RightLowerArm");
      const rightHand = group.current.getObjectByName("RightHand");
      const rightThumb = group.current.getObjectByName("RightHandThumb1");
      
      if (spine && head && rightUpperArm && rightLowerArm && rightHand && rightThumb) {
        // Initial look down at outfit
        spine.rotation.x = 0.4;
        head.rotation.x = 0.4;
        
        // Admiring sequence
        const sequence = [
          // Look down at outfit
          () => {
            spine.rotation.x = 0.4;
            head.rotation.x = 0.4;
          },
          // Start raising arm for thumbs up
          () => {
            rightUpperArm.rotation.y = -0.5;
            rightUpperArm.rotation.z = -0.8;
            rightLowerArm.rotation.x = -1.5;
            rightHand.rotation.x = 0;
            rightHand.rotation.y = 0.5;
          },
          // Complete thumbs up gesture
          () => {
            rightUpperArm.rotation.y = -0.8;
            rightUpperArm.rotation.z = -1.2;
            rightLowerArm.rotation.x = -1.8;
            rightHand.rotation.x = -0.3;
            rightHand.rotation.y = 0.7;
            rightThumb.rotation.x = -0.5;
            rightThumb.rotation.z = 0.3;
            head.rotation.y = 0.3;
            spine.rotation.y = 0.2;
          },
          // Hold the pose with slight movement
          () => {
            rightUpperArm.rotation.z -= 0.1;
            rightHand.rotation.y += 0.1;
          },
          // Return to normal position
          () => {
            spine.rotation.x = 0;
            spine.rotation.y = 0;
            head.rotation.x = 0;
            head.rotation.y = 0;
            rightUpperArm.rotation.y = 0;
            rightUpperArm.rotation.z = 0;
            rightLowerArm.rotation.x = 0;
            rightHand.rotation.x = 0;
            rightHand.rotation.y = 0;
            rightThumb.rotation.x = 0;
            rightThumb.rotation.z = 0;
            setIsAdmiring(false);
          }
        ];

        // Execute sequence with natural timing
        sequence.forEach((pose, index) => {
          setTimeout(pose, index * 800); // Increased timing for more visible poses
        });
      }
      
      lastDressChange.current = dress;
    }
  }, [dress]);
  
  // Load the dress texture
  const dressTexture = useTexture("/shopping.jpg");
  dressTexture.flipY = false;
  dressTexture.encoding = THREE.sRGBEncoding;
  
  // Create a single dress material that we'll update with colors
  const [dressMaterial, setDressMaterial] = useState(
    new THREE.MeshStandardMaterial({
      map: dressTexture,
      color: "#ffffff",
      metalness: 0.2,
      roughness: 0.7,
      side: THREE.DoubleSide,
    })
  );

  // Play animation when it changes
  useEffect(() => {
    if (animation && actions[animation]) {
      // Stop all current animations
      Object.values(actions).forEach(action => {
        if (action.isRunning()) {
          action.fadeOut(0.5);
        }
      });
      
      // Play the new animation
      actions[animation].reset().fadeIn(0.5).play();
      
      return () => {
        actions[animation].fadeOut(0.5);
      };
    }
  }, [animation, actions]);
  
  // Handle head following and breathing
  useFrame((state) => {
    if (headFollow && group.current) {
      const head = group.current.getObjectByName("Head");
      if (head) {
        head.lookAt(state.camera.position);
      }
    }

    // Enhanced breathing animation - always active unless admiring
    if (group.current) {
      const spine = group.current.getObjectByName("Spine2");
      const chest = group.current.getObjectByName("Spine1");
      if (spine && chest) {
        const time = state.clock.getElapsedTime();
        // More pronounced breathing motion
        spine.rotation.x = Math.sin(time * 1.2) * 0.07;
        chest.rotation.x = Math.sin(time * 1.2) * 0.07;
        // Subtle body sway
        if (!isAdmiring) {
          spine.rotation.y = Math.sin(time * 0.8) * 0.05;
          chest.rotation.y = Math.sin(time * 0.8) * 0.05;
        }
      }
    }
  });
  
  // Apply wireframe to all materials
  useEffect(() => {
    Object.values(materials).forEach((material) => {
      material.wireframe = wireframe;
    });
  }, [wireframe, materials]);

  // Update dress material when color changes
  useEffect(() => {
    if (dress !== "default") {
      const newMaterial = new THREE.MeshStandardMaterial({
        map: dressTexture,
        color: dress,
        metalness: 0.2,
        roughness: 0.7,
        side: THREE.DoubleSide,
      });
      setDressMaterial(newMaterial);

      // Ensure animations continue playing after color change
      if (animation && actions[animation]) {
        actions[animation].play();
      }
    }
  }, [dress, dressTexture, animation, actions]);

  return (
    <group {...props} ref={group} dispose={null}>
      <group>
        <primitive object={nodes.Hips} />
        <skinnedMesh
          geometry={nodes.Wolf3D_Body.geometry}
          material={materials.Wolf3D_Body}
          skeleton={nodes.Wolf3D_Body.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
          material={dress !== "default" ? dressMaterial : materials.Wolf3D_Outfit_Bottom}
          skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
          material={materials.Wolf3D_Outfit_Footwear}
          skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Top.geometry}
          material={dress !== "default" ? dressMaterial : materials.Wolf3D_Outfit_Top}
          skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Hair.geometry}
          material={materials.Wolf3D_Hair}
          skeleton={nodes.Wolf3D_Hair.skeleton}
        />
        <skinnedMesh
          name="EyeLeft"
          geometry={nodes.EyeLeft.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeLeft.skeleton}
          morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
        />
        <skinnedMesh
          name="EyeRight"
          geometry={nodes.EyeRight.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeRight.skeleton}
          morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
        />
        <skinnedMesh
          name="Wolf3D_Head"
          geometry={nodes.Wolf3D_Head.geometry}
          material={materials.Wolf3D_Skin}
          skeleton={nodes.Wolf3D_Head.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
        />
        <skinnedMesh
          name="Wolf3D_Teeth"
          geometry={nodes.Wolf3D_Teeth.geometry}
          material={materials.Wolf3D_Teeth}
          skeleton={nodes.Wolf3D_Teeth.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
        />
      </group>
    </group>
  );
}

// Preload the model
useGLTF.preload("/models/646d9dcdc8a5f5bddbfac913.glb");
